### ISSUE TITLE
everything good here 

### ISSUE THREAD

**Issue by Samthapa76** [JuniorDjjr/scrlog#2]
every thing i like about Scrlog but just string that threads name its too short that makes dificult to figure out which one is that 
example 
some lines are ok with 2 to 5 lines name but  scripts thread with :none_firemanssda

they hard to find please make longer string name to know exact whioch thread is that  thanks

**Comment by JuniorDjjr** [comment]
This isn't related to scrlog, the game scripts are limited to 7 characters. CLEO.log tells you what is the file name for each script, as explained on [MixMods' post](https://www.mixmods.com.br/2020/10/iii-vc-sa-scrlog-2020-3-descobrir-crash-em-mod-cleo/).

**Comment by Samthapa76** [comment]
"game scripts are limited to 7 characters" yea i know like GXT has limit but idk if i am not wrong can do more than 128 letters idk how to show you  'abcdefg' if you use apostrophe 7 to 9 letters limit but if you use quotation mark "abcdefghijklmnopqrstuvwxyz"

**Comment by JuniorDjjr** [comment]
Yes, can, but like I said, this is limited by how scripts work (game, CLEO), this isn't related to SCRLog (the SCRLog is created to simply log the script, SCRLog has access only to stored script name from game or from CLEO, that are limited to only 7 characters, if you want to make CLEO support longer script name, ask for CLEO). And like I said, you can just open CLEO.log to see the file name for respective script if you don't know what is the script file by reading the short name. SCRLog can like read CLEO.log to find the file name but is a messy solution, would be better to like make CLEO to store and expose the access to file name or something.

**Comment by Samthapa76** [comment]
you are right i saw that  

Streams
0xA8B430 - Start thread pool. There are active and inactive threads.
0xA8B42C - Pointer to the first active SCM stream.
0xA8B428 - Pointer to the first inactive script.

Each stream is 224 (0xE0) bytes in size

+0 = [void *] Pointer to the next stream.
+4 = [void *] Pointer to the previous stream.
+8 = [char] Stream name (assigned by 03A4 opcode ), char = 8

max is 8 :( and yea thanks [JuniorDjjr](https://github.com/JuniorDjjr) and i am so sorry what i said yesterday i am an idiot :(
